export const GET_MEMBER = "GET_MEMBER";
export const POST_MEMBER = "POST_MEMBER";
export const GET_FINANCIAL = "GET_FINANCIAL";
export const POST_FINANCIAL = "POST_FINANCIAL";
export const LOCATION_CHART_DATA = "LOCATION_CHART_DATA";
export const GRADUATION_YEAR_CHART_DATA = "GRADUATION_YEAR_CHART_DATA";




